#Versao
version: '3.9'
#Volumes
volumes:
  db_volume-movies:
  db_volume-review:
#Redes  
networks: 
  produto_net:
    driver: bridge
    
#Declarar as database dos dois moveis e review
services:
  rotten-potatoes:
    image: daniel10souza/rotten-potatoes-ms:v6
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks:
     - produto_net    
    environment: 
      REVIEW_SERVICE_URI: http://review:8282 
      MOVIE_SERVICE_URI: http://movies:8181       
#Dependências do Mongodb
    depends_on: 
     - database-movies
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
      MONGODB_URI: mongodb://mongouser:mongopwd@mongodb:27017/admin     
      
  database-movies:
    image: mongo:4.4.6
    ports:
     - 27017:27017
    networks:
     - produto_net
    volumes:
      - db_volume-movies:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  database-review:
    image: postgres:14.0
    ports:
     - 5432:5432
    networks:
     - produto_net
    volumes:
      - db_volume-review:/data/db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: Pg@123;
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgredb
      ConnectionStrings__MyConnection: Host=postgredb;Database=pguser;Username=pguser;Password=Pg@123;


  #Declarar as aplicações
  api-review:
    image: daniel10souza/review:v3
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
     - 8282:8282  
    networks:
     - produto_net 
    environment: 
      REVIEW_SERVICE_URI: http://review:8282      


  
  api-movie:
    image: daniel10souza/movie:v4
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
     - 8181:8181       
    networks:
     - produto_net
    environment: 
      MOVIE_SERVICE_URI: http://movies:8181