version: '3.8'
#Volumes fixos
volumes:
  mongo_vol:
  post_vol:
#rede cominicação
networks:
  produto_net:
    driver: bridge

#Services de banco
services:
  mongo_db:
    image: mongo:4.4.3
    networks:
      - produto_net
    volumes:
      - mongo_vol:/base/db
    environment:
      MONGODB_HOST: mongo_db
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  post_db:
    image: postgres:latest
    networks:
       - produto_net
    volumes:
      - post_vol:/vol/postgresql/data
    environment:
      POSTGRES_DB: pgDB
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgsenha

#Aplicação
  api:
    image: daniel10souza/rotten-potatoes-ms:v2
    ports:
      - 8080:8080
    networks:
      - produto_net
    depends_on:
      - movies
      - review
    environment:
      MONGODB_HOST: mongo_db
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
      MOVIE_SERVICE_URI: http://movies:8181/
      REVIEW_SERVICE_URI: http://review:80/

  movies:
    image: daniel10souza/movies:v4
    networks:
      - produto_net
    depends_on:
      - mongo_db
    environment:
      MONGODB_URI: mongo_db://mongouser:mongopwd@mongo_db:27017/admin

  review:
    image: daniel10souza/review:v1
    networks:
      - produto_net
    depends_on:
      - post_db
    environment:
      ConnectionStrings__MyConnection: Host=post_db;Database=pgDB;Username=pguser;Password=pgsenha;