#Versão
networks: 
  produto_net:
    driver: bridge
version: '3.5'
services:
  rotten:
    image: daniel10souza/rotten-potatoes-ms:v1
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks:
     - produto_net      
#Declarar as database dos dois moveis e review

  database-review:
    image: postgres:14.0
    env_file: db-review/database.conf
    networks:
     - produto_net
    volumes:
      - db_volume-review:/data/db

  database-movies:
    image: mongo:4.4.6
    env_file: db-movies/database.conf
    networks:
     - produto_net
    volumes:
      - db_volume-movies:/data/db      

#Dependências

    depends_on: 
     - database-review

  #Declarar as aplicações
  api-review:
    image: daniel10souza/review:v1
    env_file: env-review/env.conf
    ports:
      - 8282:8282
    volumes:
      - ./src/app:/src/app/

    depends_on: 
     - database-movies
    
  api-movie:
    image: daniel10souza/movie:v1
    env_file: env-movies/env.conf
    networks:
     - produto_net    
    ports:
      - 8181:8181
    volumes:
      - ./src/app:/src/app/


volumes:
  db_volume-movies:
  db_volume-review: